flags: {}
packages:
- '.'
extra-deps: [semigroups-0.17.0.1
            ,QuickCheck-2.8.1
            ,hspec-2.2.1
            ,hspec-core-2.2.1
            ,hspec-discover-2.2.1
            ,hspec-expectations-0.7.2
            ]
resolver: lts-3.2
