flags: {}
packages:
- '.'
extra-deps: [semigroups-0.17.0.1
            ,QuickCheck-2.8.1
            ,hspec-2.2.1
            ,hspec-core-2.2.1
            ,hspec-discover-2.2.1
            ,hspec-expectations-0.7.2
            ,cmdargs-0.10.13
            ,hashable-1.2.4.0
            ,nats-1.1
            ,primes-0.2.1.0
            ,tagged-0.8.2
            ,text-1.2.2.0
            ,unordered-containers-0.2.6.0
            ,HUnit-1.3.1.0
            ,network-2.6.2.1
            ,random-1.1
            ]
resolver: lts-4.1
